### ISSUE TITLE
Add maximum size for indicator text

### ISSUE THREAD

**Issue by 7hat3eird0ne** [Prevter/gd-go-indicator#1]
So right now the amount of characters specifies the size. That is ok, but when u have a 2 character long indicator it is significantly bigger than 3 character long indicator

would it be possible to make it so that i can set it so that if an indicator text is shorter than certain amount, it will make the size of the smallest characters size allowed instead of the actual size? (So in this case anything shorter than 3 could become 3)

**Comment by Prevter** [comment]
Added "Label Scale" option
(global per level because I really didn't want to remake whole UI to add another input for each indicator setting in the list :P)
